import DAO.AlunoDAO;
import model.Aluno;
import DAO.Conexao;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author tavio
 */
public class cadastro_aluno extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(cadastro_aluno.class.getName());

    /**
     * Creates new form cadastro_aluno
     */
    public cadastro_aluno() {
        initComponents();
    }

    // Variável global (dentro da classe)
    private int linhaEmEdicao = -1; // -1 significa que não estamos editando

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrp_Cursos = new javax.swing.ButtonGroup();
        lbl_Curso = new javax.swing.JLabel();
        rdo_ADS = new javax.swing.JRadioButton();
        rdo_CienciaDados = new javax.swing.JRadioButton();
        rdo_SegInfo = new javax.swing.JRadioButton();
        rdo_Gcom = new javax.swing.JRadioButton();
        btn_Salvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Alunos = new javax.swing.JTable();
        lbl_Nome = new javax.swing.JLabel();
        txt_Nome = new javax.swing.JTextField();
        btn_Apagar = new javax.swing.JButton();
        lbl_Idade = new javax.swing.JLabel();
        txt_Idade = new javax.swing.JTextField();
        btn_Alterar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_Curso.setText("Escolha seu curso:");

        btnGrp_Cursos.add(rdo_ADS);
        rdo_ADS.setText("ADS");

        btnGrp_Cursos.add(rdo_CienciaDados);
        rdo_CienciaDados.setText("Ciência de Dados");

        btnGrp_Cursos.add(rdo_SegInfo);
        rdo_SegInfo.setText("Seg. da Informação");

        btnGrp_Cursos.add(rdo_Gcom);
        rdo_Gcom.setText("G. Com.");

        btn_Salvar.setText("Salvar");
        btn_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalvarActionPerformed(evt);
            }
        });

        tbl_Alunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Idade", "Curso"
            }
        ));
        jScrollPane1.setViewportView(tbl_Alunos);

        lbl_Nome.setText("Nome");

        btn_Apagar.setText("Apagar");
        btn_Apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ApagarActionPerformed(evt);
            }
        });

        lbl_Idade.setText("Idade");

        btn_Alterar.setText("Alterar");
        btn_Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btn_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_Curso)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_Nome)
                                    .addComponent(lbl_Idade, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txt_Idade, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txt_Nome)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_Alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Apagar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(rdo_ADS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdo_CienciaDados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdo_SegInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdo_Gcom)
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Nome)
                    .addComponent(txt_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Idade)
                    .addComponent(txt_Idade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_Curso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdo_ADS)
                    .addComponent(rdo_CienciaDados)
                    .addComponent(rdo_SegInfo)
                    .addComponent(rdo_Gcom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Salvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Apagar)
                    .addComponent(btn_Alterar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalvarActionPerformed
        // Dados dos campos
        String nome = txt_Nome.getText();
        int idade = Integer.parseInt(txt_Idade.getText());
        String curso;

        if (rdo_ADS.isSelected()) {
            curso = "ADS";
        } else if (rdo_CienciaDados.isSelected()) {
            curso = "Ciência de Dados";
        } else if (rdo_Gcom.isSelected()) {
            curso = "Gestão Comercial";
        } else {
            curso = "Segurança da Informação";
        }

        //gerencia os dados da tabela
        DefaultTableModel tabela = (DefaultTableModel) tbl_Alunos.getModel();

        if (linhaEmEdicao != -1) {
            // Estamos editando: atualiza a linha existente
            tabela.setValueAt(nome, linhaEmEdicao, 0);
            tabela.setValueAt(idade, linhaEmEdicao, 1);
            tabela.setValueAt(curso, linhaEmEdicao, 2);

            linhaEmEdicao = -1; // reseta para modo adicionar
        } else {
            // Estamos adicionando um novo
            Aluno a = new Aluno(txt_Nome.getText(), idade, curso);
            tabela.addRow(a.obterDados()); //colocando os dados na tabela
            /* OUTRA FORMA DE PEGAR OS DADOS
            a.setNome(txt_Nome.getText());
            a.setIdade(idade);
            a.setCurso(curso);
            */
            //colocando os dados no banco
            AlunoDAO aDAO = new AlunoDAO();
            aDAO.inserir(a);
        }

        // Limpa campos
        txt_Nome.setText("");
        txt_Idade.setText("");
        btnGrp_Cursos.clearSelection();

    }//GEN-LAST:event_btn_SalvarActionPerformed

    private void btn_ApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ApagarActionPerformed
        // Obtém a linha selecionada
        int linhaSelecionada = tbl_Alunos.getSelectedRow();

        // Verifica se alguma linha está realmente selecionada
        if (linhaSelecionada != -1) {
            DefaultTableModel tabela = (DefaultTableModel) tbl_Alunos.getModel();
            tabela.removeRow(linhaSelecionada); // remove a linha
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma linha para apagar!");
        }
    }//GEN-LAST:event_btn_ApagarActionPerformed

    private void btn_AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AlterarActionPerformed
        // Obtém a linha selecionada
        //O método getSelectedRow() retorna -1 quando nenhuma linha está selecionada
        int linhaSelecionada = tbl_Alunos.getSelectedRow();

        // Verifica se alguma linha está realmente selecionada
        if (linhaSelecionada != -1) {
            DefaultTableModel tabela = (DefaultTableModel) tbl_Alunos.getModel();

            txt_Nome.setText(tabela.getValueAt(linhaSelecionada, 0).toString());
            txt_Idade.setText(tabela.getValueAt(linhaSelecionada, 1).toString());

            // Curso (radio button)
            String curso = tabela.getValueAt(linhaSelecionada, 2).toString();
            switch (curso) {
                case "ADS":
                    rdo_ADS.setSelected(true);
                    break;
                case "Ciência de Dados":
                    rdo_CienciaDados.setSelected(true);
                    break;
                case "Gestão Comercial":
                    rdo_Gcom.setSelected(true);
                    break;
                case "Segurança da Informação":
                    rdo_SegInfo.setSelected(true);
                    break;
            }

            // Guarda a linha que estamos editando
            linhaEmEdicao = linhaSelecionada;
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma linha para alterar!");
        }
    }//GEN-LAST:event_btn_AlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        Conexao c = new Conexao();
        c.getConexao();
        
        /* TESTANDO A INSERÇÃO
        Aluno a = new Aluno();
        a.setNome("Marcos");
        a.setIdade((int)30);
        a.setCurso("ADS");
        AlunoDAO aDAO = new AlunoDAO();
        aDAO.inserir(a);
        */
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new cadastro_aluno().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGrp_Cursos;
    private javax.swing.JButton btn_Alterar;
    private javax.swing.JButton btn_Apagar;
    private javax.swing.JButton btn_Salvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Curso;
    private javax.swing.JLabel lbl_Idade;
    private javax.swing.JLabel lbl_Nome;
    private javax.swing.JRadioButton rdo_ADS;
    private javax.swing.JRadioButton rdo_CienciaDados;
    private javax.swing.JRadioButton rdo_Gcom;
    private javax.swing.JRadioButton rdo_SegInfo;
    private javax.swing.JTable tbl_Alunos;
    private javax.swing.JTextField txt_Idade;
    private javax.swing.JTextField txt_Nome;
    // End of variables declaration//GEN-END:variables
}
